version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: payment-mongodb-new
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_RS_ENABLED: "true"
    entrypoint: ./entrypoint.sh
    volumes:
      - database:/data/db

volumes:
  database: