apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-config
  namespace: {{ .Values.namespace }}
data:
  PORT: '3000'
  HOST: {{ .Values.config.grpc.host }}
  GRPC_AUTH_URL: {{ .Values.config.grpc.authUrl }}
  GRPC_USER_URL: {{ .Values.config.grpc.userUrl }}
  GRPC_ROLE_URL: {{ .Values.config.grpc.roleUrl }}
  GRPC_PERMISSION_URL: {{ .Values.config.grpc.permissionUrl }}
  GRPC_VEHICLE_URL: {{ .Values.config.grpc.vehicleUrl }}
  GRPC_BRAND_URL: {{ .Values.config.grpc.brandUrl }}
  GRPC_COLOR_URL: {{ .Values.config.grpc.colorUrl }}
  GRPC_ORDER_URL: {{ .Values.config.grpc.orderUrl }}
  GRPC_PAYMENT_URL: {{ .Values.config.grpc.paymentUrl }}
  MAIL_TRACKING_URL: {{ .Values.config.grpc.mailTrackingUrl }}
