apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: rickwalking/payment:latest
          ports:
            - containerPort: 3000  
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: payment-env
                  key: DATABASE_URL
            - name: MERCADOPAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: payment-env
                  key: MERCADOPAGO_ACCESS_TOKEN